"""Tests for volnix.templates.registry — template registration and discovery."""


def test_register_template(): ...


def test_get_template(): ...


def test_list_templates(): ...


def test_discover_builtin(): ...
