"""Platform Session primitive (PMF Plan Phase 4C Step 4).

A ``Session`` is a sibling of ``World`` and ``Run``. Within a single
world, ≥1 runs are grouped under 1 session; a session spans multiple
activations, persists memory across runs, and survives process
restarts (``SessionManager`` in Step 5 owns the SQLite backing store).

This module defines the *types* only. ``SessionManager`` (Step 5)
drives lifecycle. Step 6 stamps ``session_id`` onto events + envelopes
emitted during a session.

See ``internal_docs/pmf/phase-4c-platform-hardening.md`` §Step 4 for
the full roadmap.
"""

from __future__ import annotations

import enum
from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, model_validator

from volnix.core.types import SessionId, WorldId

# ``SeedStrategy`` and ``SessionCheckpointKind`` are intentionally
# NOT re-exported via ``__all__`` during 0.2.0 (D4b — "earn the
# export"). ``from volnix.core.session import *`` returns only the
# Session value object + public enums.
__all__ = [
    "Session",
    "SessionId",
    "SessionStatus",
    "SessionType",
]


class SessionStatus(enum.StrEnum):
    """Lifecycle status of a session.

    Transition graph (enforced by ``SessionManager`` in Step 5):

    - ``ACTIVE`` → ``PAUSED`` | ``COMPLETED`` | ``ABANDONED``
    - ``PAUSED`` → ``ACTIVE`` | ``ABANDONED``
    - ``COMPLETED`` / ``ABANDONED`` are terminal.
    """

    ACTIVE = "active"
    PAUSED = "paused"
    COMPLETED = "completed"
    ABANDONED = "abandoned"


class SessionType(enum.StrEnum):
    """Session-type taxonomy (PMF Plan D4).

    - ``BOUNDED``: fixed end condition known up front (e.g. "run N
      turns then end"). Classic research-style evaluation.
    - ``OPEN``: no predetermined end; the consumer ends the session
      explicitly when the goal is reached.
    - ``RESUMABLE``: like ``OPEN`` but explicitly designed for
      pause/resume cycles across process restarts (the Rehearse
      multi-month-continuity use case).
    """

    BOUNDED = "bounded"
    OPEN = "open"
    RESUMABLE = "resumable"


class SeedStrategy(enum.StrEnum):
    """How the session chooses its deterministic seed (PMF Plan D5).

    Not part of the 0.2.0 public API (see Step-4 D4b) — ``SessionManager``
    accepts the strategy as a string. Promote to public when a
    consumer needs to type-hint against the enum.

    - ``INHERIT``: same seed as the world. Every session starts from
      the same deterministic point; cross-session state evolves
      through real input only. Default.
    - ``FRESH``: ``world_seed ^ hash(session_id)``. Different
      stochastic paths per session; continuity only via persisted
      state.
    - ``EXPLICIT``: caller supplies the seed directly.
    """

    INHERIT = "inherit"
    FRESH = "fresh"
    EXPLICIT = "explicit"


class SessionCheckpointKind(enum.StrEnum):
    """Discriminator for ``SessionCheckpointEntry`` (PMF Plan D4
    audit-fold D-Find-6 + review H2).

    Three kinds share one entry class: pause and resume are
    significant transitions, not separate entry types. Modelled as
    a ``StrEnum`` so Step-5 code doing ``match entry.kind:`` gets
    exhaustive checks — ``Literal[...]`` would miss that.

    Not part of the 0.2.0 public API (D4b).
    """

    CHECKPOINT = "checkpoint"
    PAUSE = "pause"
    RESUME = "resume"


class Session(BaseModel):
    """Platform Session primitive.

    A value object (frozen). Lifecycle (start / pause / resume / end)
    is driven by ``SessionManager`` — this class carries the data,
    not the verbs.

    **Construction is SessionManager's job.** While Pydantic frozen
    semantics don't technically hide the constructor, direct
    construction by a library consumer is unsupported outside of
    tests: the ``session_id`` generation, seed derivation, and
    ledger-append side effects all live on ``SessionManager``.
    A ``Session`` instantiated outside that code path will not
    appear in the ledger or the session store (D4h).

    Attributes:
        session_id: Globally unique session identifier
            (``uuid4().hex[:12]`` generated by ``SessionManager.start()``
            — pattern matches ``run_id`` / ``world_id``).
        world_id: The world this session belongs to. Cross-world
            sessions are out of scope (PMF Plan §10).
        session_type: One of ``bounded`` | ``open`` | ``resumable``.
        status: Current lifecycle status. ``ACTIVE`` at creation;
            terminal statuses are ``COMPLETED`` / ``ABANDONED``.
        seed_strategy: How the session's seed was chosen.
        seed: The actual deterministic seed in use. Always populated
            (the strategy decides how — ``INHERIT`` copies the world
            seed; ``FRESH`` derives; ``EXPLICIT`` records the
            caller's value).
        start_tick: Logical tick at session start. Cross-run tick
            continuity (PMF Plan G8) carries this into the next
            run's ``SimulationRunner`` via Step 6.
        end_tick: Logical tick at session end (``None`` while
            active, and may remain ``None`` when a paused session
            is abandoned across a process restart without a run in
            progress — review M8 / D4k).
        created_at: Wall-clock timestamp of session creation.
        updated_at: Wall-clock timestamp of the last lifecycle
            transition. ``SessionManager`` bumps this on every
            status change. A freshly-created session has
            ``updated_at == created_at`` (shared stamp — review
            H3 / D4i).

    Type note on ``created_at`` / ``updated_at``: the declared
    annotation is ``datetime | None``, but on a constructed instance
    both are always ``datetime``. The ``None`` branch exists so the
    ``mode="before"`` validator can detect the "missing" case and
    fill both fields from one shared ``now()`` call. mypy-strict
    consumers accessing ``session.created_at`` in a hot path should
    either narrow with ``assert session.created_at is not None`` or
    wrap the access in a helper that guarantees the post-validation
    invariant. ``SessionManager`` (Step 5) is the construction site
    for platform code and always supplies both timestamps.
        metadata: Free-form per-session metadata bag. Consumers
            (e.g., Rehearse) layer their own schema on top (e.g.,
            product-scoped labels for observability filters). Keep
            keys product-namespaced to avoid cross-consumer
            collisions.
    """

    model_config = ConfigDict(frozen=True)

    session_id: SessionId
    world_id: WorldId
    session_type: SessionType
    status: SessionStatus = SessionStatus.ACTIVE
    seed_strategy: SeedStrategy = SeedStrategy.INHERIT
    seed: int
    start_tick: int = 0
    end_tick: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _stamp_timestamps(cls, data: Any) -> Any:
        """Seed ``created_at`` / ``updated_at`` from ONE ``now()``
        call when either is missing (review H3 / D4i). Explicit
        caller-supplied values win.
        """
        if not isinstance(data, dict):
            return data
        if data.get("created_at") is None or data.get("updated_at") is None:
            now = datetime.now(UTC)
            if data.get("created_at") is None:
                data["created_at"] = now
            if data.get("updated_at") is None:
                data["updated_at"] = data["created_at"]
        return data
