"""Persistent runtime state for internal actors.

ActorState is mutable (unlike ActorDefinition which is frozen).
Updated deterministically after each committed event.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from terrarium.core.types import ActorId, EntityId


class WaitingFor(BaseModel, frozen=True):
    """Describes what an actor is waiting for."""

    description: str
    since: float  # logical_time when waiting started
    patience: float  # duration before frustration increases
    escalation_action: str | None = None


class ScheduledAction(BaseModel, frozen=True):
    """An action scheduled for a future logical time."""

    logical_time: float
    action_type: str
    description: str
    target_service: str | None = None
    payload: dict[str, Any] = Field(default_factory=dict)


class ActorBehaviorTraits(BaseModel, frozen=True):
    """Normalized behavioral traits extracted from persona at compile time.

    These structured fields are used for tier classification routing.
    The persona dict remains freeform for LLM prompt realism.
    """

    cooperation_level: float = 0.5  # 0.0=hostile, 1.0=fully cooperative
    deception_risk: float = 0.0  # 0.0=honest, 1.0=highly deceptive
    authority_level: float = 0.0  # 0.0=no authority, 1.0=full authority
    stakes_level: float = 0.3  # 0.0=trivial, 1.0=critical
    ambient_activity_rate: float = 0.1  # 0.0=never initiates, 1.0=constantly active


# ---------------------------------------------------------------------------
# Collaborative Communication types
# ---------------------------------------------------------------------------


class Subscription(BaseModel, frozen=True):
    """What this actor is listening to in the world.

    Generated by the compiler at compile time based on actor role
    and service topology. NOT hardcoded — LLM infers appropriate
    subscriptions from world context.

    Attributes:
        service_id: Which service to listen to (e.g. "chat", "email", "tickets").
        filter: Service-specific match criteria (e.g. {"channel": "#research"}).
        sensitivity: How urgently this actor should react to matching events.
    """

    service_id: str
    filter: dict[str, Any] = Field(default_factory=dict)
    # V2: batch/passive unused in MVP — all subscriptions activate immediately
    sensitivity: Literal["immediate", "batch", "passive"] = "immediate"


class InteractionRecord(BaseModel, frozen=True):
    """One interaction this actor is aware of.

    Provides structured context for the LLM prompt so it sees
    a conversation with attribution, not a flat event log.

    Attributes:
        tick: Logical time of the interaction.
        actor_id: Who performed the action.
        actor_role: Role of the acting agent (e.g. "researcher-A").
        action: Tool name (e.g. "slack_post_message").
        summary: Compact natural language description of what happened.
        source: How this actor learned about it.
        event_id: Reference to the original WorldEvent.
        reply_to: Event ID this was a reply to (threading).
        channel: Communication channel (e.g. "#research").
        intended_for: Tagged recipient roles (for token efficiency).
    """

    tick: float
    actor_id: str
    actor_role: str
    action: str
    summary: str
    source: Literal["self", "observed", "notified"]
    event_id: str
    reply_to: str | None = None
    channel: str | None = None
    intended_for: list[str] = Field(default_factory=list)


class ActorState(BaseModel):
    """Persistent mutable state for an internal actor.

    This is NOT frozen -- it is updated deterministically during simulation.
    One ActorState per internal actor, managed by AgencyEngine.
    """

    actor_id: ActorId
    role: str
    actor_type: str = "internal"  # "external" | "internal" | "observer"
    autonomous: bool = False  # Autonomous agents work in a loop; reactive actors respond when triggered

    # Identity (generated at compile time, immutable during run)
    persona: dict[str, Any] = Field(default_factory=dict)
    behavior_traits: ActorBehaviorTraits = Field(default_factory=ActorBehaviorTraits)

    # Goal (v1: single active goal)
    current_goal: str | None = None
    goal_strategy: str | None = None

    # Reactive state (updated during simulation)
    waiting_for: WaitingFor | None = None
    frustration: float = 0.0  # 0.0 - 1.0
    urgency: float = 0.3  # 0.0 - 1.0

    # Memory
    pending_notifications: list[str] = Field(default_factory=list)
    recent_interactions: list[InteractionRecord] = Field(default_factory=list)

    # Scheduling
    scheduled_action: ScheduledAction | None = None

    # Activation
    activation_tier: int = 0  # 0, 1, 2, or 3
    watched_entities: list[EntityId] = Field(default_factory=list)

    # Collaborative communication
    subscriptions: list[Subscription] = Field(default_factory=list)
    pending_tasks: list[str] = Field(default_factory=list)
    goal_context: str | None = None
    batch_notification_count: int = 0
    batch_threshold: int = 3

    # Configuration
    max_recent_interactions: int = 20
