import { useRef } from 'react';
import { useSearchParams, Link } from 'react-router';
import { ChevronRight, Hexagon } from 'lucide-react';
import { useComparison } from '@/hooks/queries/use-compare';
import { QueryGuard } from '@/components/feedback/query-guard';
import { EmptyState } from '@/components/feedback/empty-state';
import { MetricDiffTable } from '@/pages/compare/metric-diff-table';
import { DivergenceTimeline } from '@/pages/compare/divergence-timeline';
import { ScoreComparisonBars } from '@/pages/compare/entity-diff';
import { ExportButton } from '@/pages/compare/export-button';
import type { RunComparison } from '@/types/domain';

function CompareContent({ runIds }: { runIds: string[] }) {
  const query = useComparison(runIds);
  const exportRef = useRef<HTMLDivElement | null>(null);

  return (
    <QueryGuard query={query}>
      {(data: RunComparison) => {
        const tagLine = data.runs
          .map((r) => r.tags[0] ?? r.id)
          .join(' vs ');
        const firstRun = data.runs[0];
        const worldLine = firstRun
          ? `${firstRun.world_name} · ${firstRun.reality_preset} · ${firstRun.behavior} · ${firstRun.mode}`
          : '';

        return (
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-lg font-medium text-text-primary">
                  Comparing: {tagLine}
                </h1>
                {worldLine && (
                  <p className="text-sm text-text-muted">World: {worldLine}</p>
                )}
              </div>
              <ExportButton targetRef={exportRef} />
            </div>

            <div ref={exportRef} className="space-y-6 rounded bg-bg-surface p-6">
              <div className="flex items-center gap-2 border-b border-bg-elevated pb-4">
                <Hexagon size={20} className="text-info" />
                <span className="text-sm font-medium text-text-primary">Terrarium</span>
                {worldLine && (
                  <span className="text-xs text-text-muted">— {worldLine}</span>
                )}
              </div>

              <MetricDiffTable metrics={data.metrics} runs={data.runs} />
              <DivergenceTimeline points={data.divergence_points} runs={data.runs} />
              <ScoreComparisonBars metrics={data.metrics} runs={data.runs} />

              <div className="border-t border-bg-elevated pt-4 text-center text-xs text-text-muted">
                Generated by Terrarium Dashboard · github.com/terrarium
              </div>
            </div>
          </div>
        );
      }}
    </QueryGuard>
  );
}

export function ComparePage() {
  const [searchParams] = useSearchParams();
  const runIds = searchParams.get('runs')?.split(',').filter(Boolean) ?? [];

  return (
    <div className="space-y-4">
      <nav className="flex items-center gap-1 text-sm text-text-muted">
        <Link to="/" className="hover:text-text-primary">
          Terrarium
        </Link>
        <ChevronRight size={14} />
        <span className="text-text-secondary">Compare</span>
      </nav>

      {runIds.length < 2 ? (
        <EmptyState
          title="Select at least 2 runs to compare"
          description="Use the run list to select runs for comparison."
        />
      ) : (
        <CompareContent runIds={runIds} />
      )}
    </div>
  );
}
