"""Live Test: Natural Language World Creation

Simulates the user flow:
    terrarium create "A support team with email for 10 customers" --reality messy

This test:
1. Takes an NL description (like CLI would receive)
2. Sends it to the real Gemini LLM for interpretation
3. LLM generates a structured world definition (services, actors, policies, seeds)
4. LLM generates compiler settings (reality, behavior, fidelity)
5. The YAML parser processes the LLM output
6. Service resolution finds matching packs
7. WorldPlan is assembled
8. Entities and actors are generated by LLM from service schemas
9. Seeds are expanded by LLM into concrete entity modifications
10. Everything is populated into StateEngine

Run with:
    source .env && pytest tests/live/test_nl_create_world.py -v -s
"""
from __future__ import annotations

import json

import pytest
import yaml

from terrarium.engines.world_compiler.plan_reviewer import PlanReviewer


@pytest.mark.asyncio
class TestNLCreateWorld:
    """User describes a world in natural language → Terrarium creates it."""

    async def test_nl_support_team(self, live_app) -> None:
        """terrarium create 'A support team with email, 10 customers, some frustrated'"""
        compiler = live_app.registry.get("world_compiler")

        print("\n" + "=" * 70)
        print("FLOW 1: NL DESCRIPTION → LLM INTERPRETATION → WORLD")
        print("=" * 70)

        # Step 1: User provides NL description (like CLI input)
        description = (
            "A customer support team using email. "
            "10 customers, some are frustrated from slow resolution times. "
            "2 support agents. Policies: escalate if SLA breached."
        )
        print(f"\n📝 User input: {description}")

        # Step 2: Compile from NL — calls real Gemini LLM
        print("\n⏳ Sending to Gemini for NL interpretation...")
        plan = await compiler.compile_from_nl(
            description,
            reality="messy",
            behavior="dynamic",
        )

        # Step 3: Show what LLM generated
        print("\n✅ LLM interpreted the description:")
        print(f"   World name: {plan.name}")
        print(f"   Description: {plan.description}")
        print(f"   Services: {plan.get_service_names()}")
        print(f"   Actors ({len(plan.actor_specs)}):")
        for spec in plan.actor_specs:
            print(f"     - {spec.get('role')} x{spec.get('count', 1)} ({spec.get('type', '?')})")
        print(f"   Seeds: {plan.seeds}")
        print(f"   Policies: {[p.get('name', '?') for p in plan.policies]}")
        print(f"   Mission: {plan.mission}")
        print(f"   Reality: staleness={plan.conditions.information.staleness}")
        print(f"   Source: {plan.source}")

        # Step 4: Show the generated YAML (what user could export)
        reviewer = PlanReviewer()
        yaml_output = reviewer.to_yaml(plan)
        print("\n" + "-" * 40)
        print("GENERATED WORLD DEFINITION (YAML):")
        print("-" * 40)
        print(yaml_output[:1500])

        # Assertions
        assert plan.name, "LLM should generate a world name"
        assert plan.description, "LLM should expand the description"
        assert plan.actor_specs, "LLM should create actor specs"
        assert plan.source == "nl"

    async def test_nl_ecommerce_world(self, live_app) -> None:
        """terrarium create 'An e-commerce store with payments and order management'"""
        compiler = live_app.registry.get("world_compiler")

        print("\n" + "=" * 70)
        print("FLOW 1b: DIFFERENT DOMAIN — E-COMMERCE")
        print("=" * 70)

        description = (
            "An e-commerce company with payment processing via Stripe, "
            "order management with tickets, and customer email support. "
            "50 customers making purchases, 5 support agents."
        )
        print(f"\n📝 User input: {description}")

        print("\n⏳ Sending to Gemini for NL interpretation...")
        plan = await compiler.compile_from_nl(
            description,
            reality="hostile",
            behavior="dynamic",
        )

        print(f"\n✅ LLM created world: {plan.name}")
        print(f"   Services: {plan.get_service_names()}")
        print(f"   Actors: {len(plan.actor_specs)}")
        print(f"   Reality preset: hostile → friction.uncooperative={plan.conditions.friction.uncooperative}")

        assert plan.name
        assert plan.actor_specs
