import { useRef } from 'react';
import { useSearchParams, Link } from 'react-router';
import { ChevronRight, Hexagon } from 'lucide-react';
import { useComparison } from '@/hooks/queries/use-compare';
import { QueryGuard } from '@/components/feedback/query-guard';
import { EmptyState } from '@/components/feedback/empty-state';
import { MetricDiffTable } from '@/pages/compare/metric-diff-table';
import { ScoreComparisonBars } from '@/pages/compare/entity-diff';
import { ExportButton } from '@/pages/compare/export-button';
import { capitalize } from '@/lib/formatters';
import type { CompareResponse } from '@/types/api';

function CompareContent({ runIds }: { runIds: string[] }) {
  const query = useComparison(runIds);
  const exportRef = useRef<HTMLDivElement | null>(null);

  return (
    <QueryGuard query={query}>
      {(data: CompareResponse) => {
        const tagLine = data.run_ids.map((id) => capitalize(data.labels[id] ?? id)).join(' vs ');

        return (
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-lg font-medium text-text-primary">
                  Comparing: {tagLine}
                </h1>
              </div>
              <ExportButton targetRef={exportRef} />
            </div>

            <div ref={exportRef} className="space-y-6 rounded-2xl border border-border/30 bg-gradient-to-br from-bg-surface to-bg-elevated/20 p-6 shadow-md">
              <div className="flex items-center gap-2 border-b border-border/20 pb-4">
                <div className="rounded-lg bg-accent/10 p-1.5"><Hexagon size={20} className="text-info" /></div>
                <span className="text-sm font-medium text-text-primary">Volnix</span>
              </div>

              <MetricDiffTable metrics={data.scores.metrics} labels={data.labels} runIds={data.run_ids} />
              <ScoreComparisonBars metrics={data.scores.metrics} labels={data.labels} runIds={data.run_ids} />

              <div className="border-t border-border/20 pt-4 text-center text-xs text-text-muted">
                Generated by Volnix Dashboard · github.com/volnix
              </div>
            </div>
          </div>
        );
      }}
    </QueryGuard>
  );
}

export function ComparePage() {
  const [searchParams] = useSearchParams();
  const runIds = searchParams.get('runs')?.split(',').filter(Boolean) ?? [];

  return (
    <div className="space-y-4">
      <nav className="flex items-center gap-1 text-sm text-text-muted">
        <Link to="/" className="hover:text-text-primary">
          Volnix
        </Link>
        <ChevronRight size={14} />
        <span className="text-text-secondary">Compare</span>
      </nav>

      {runIds.length < 2 ? (
        <EmptyState
          title="Select at least 2 runs to compare"
          description="Use the run list to select runs for comparison."
        />
      ) : (
        <CompareContent runIds={runIds} />
      )}
    </div>
  );
}
